### ISSUE TITLE
Add stale bot for older issues in all repos

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Open-Sentencing-Model#11]
Use a stale action to alert maintainers to issues and PRs that have been sitting idle for a while. The staleness is reset if somebody comments on the issue. This forces the team to address outstanding issues and PRs.

https://github.com/actions/stale

Default configuration:

* Add a label "Stale" on issues and pull requests after 60 days of inactivity
* Close the stale issues and pull requests after 7 days of inactivity
* If an update/comment occur on stale issues or pull requests, the stale label will be removed and the timer will restart

**Comment by sforsyth089** [comment]
I'm happy to review. There are a couple I cannot merge: the model and report generator.
